# Generated by Django 2.1.1 on 2020-03-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='situps_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='squats_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
