# Generated by Django 2.1.1 on 2020-03-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_auto_20200318_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='dips_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='pullups_count',
            field=models.IntegerField(default=0),
        ),
    ]
