# Generated by Django 2.1.1 on 2020-04-04 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20200329_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=100)),
                ('is_time', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('competition_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.CompetitionExercise')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='competitionexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.Exercise'),
        ),
    ]
