# Generated by Django 2.1.1 on 2020-04-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_competitionexercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionexercise',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
